[package]
name = "age-plugin-phone"
description = "Offline phone-backed identity plugin for age"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
age-core.workspace = true
age-plugin.workspace = true
age-plugin-phone-protocol = { path = "../protocol" }
age-plugin-phone-recipient-p256 = { path = "../recipient-p256" }
age-plugin-phone-transport = { path = "../transport" }
base64.workspace = true
bech32.workspace = true
clap.workspace = true
minicbor.workspace = true
nokhwa.workspace = true
p256.workspace = true
qrcode.workspace = true
rand_core.workspace = true
rqrr.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
nokhwa = { workspace = true, features = ["input-avfoundation"] }

[target.'cfg(target_os = "linux")'.dependencies]
nokhwa = { workspace = true, features = ["input-v4l"] }

[target.'cfg(target_os = "windows")'.dependencies]
age-plugin-phone-windows-cng = { path = "../windows-cng" }
age-plugin-phone-windows-storage = { path = "../windows-storage" }
nokhwa = { workspace = true, features = ["input-msmf"] }
windows-sys = { workspace = true, features = ["Win32_System_Threading"] }


[lints]
workspace = true
