[package]
name = "age-plugin-phone"
description = "Offline phone-backed identity plugin for age"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
age-core.workspace = true
age-plugin.workspace = true
age-plugin-phone-protocol = { path = "../protocol" }
clap.workspace = true
p256.workspace = true
qrcode.workspace = true
rand_core.workspace = true
thiserror.workspace = true


[lints]
workspace = true
